version: '3'

services:
  main:
    build:
      context: .
      dockerfile: Dockerfile
      target: Production
    image: github-react-app
    container_name: github-react-app
    restart: unless-stopped
    env_file: ./config/.env
    environment:
      - NODE_ENV=production
    ports:
      - 8080:8080
    volumes:
      - .:/home/node/github-react-app
      - node_modules:/home/node/github-react-app/node_modules
    command: node ./build/src/index.js

volumes:
  node_modules: